//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CircleA", ReplyAction="*")]
        double CircleA(double firstNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CircleA", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CircleAAsync(double firstNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TriangleA", ReplyAction="*")]
        double TriangleA(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TriangleA", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TriangleAAsync(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareA", ReplyAction="*")]
        double SquareA(double firstNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquareA", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SquareAAsync(double firstNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RectangleA", ReplyAction="*")]
        double RectangleA(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RectangleA", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RectangleAAsync(double firstNumber, double secondNumber);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse ConvertToBraille(CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse> ConvertToBrailleAsync(CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValueCount", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.GetValueCountResponse GetValueCount(CalculatorWebApplication.CalculatorService.GetValueCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValueCount", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetValueCountResponse> GetValueCountAsync(CalculatorWebApplication.CalculatorService.GetValueCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBraille", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.ConvertToBrailleRequestBody Body;
        
        public ConvertToBrailleRequest() {
        }
        
        public ConvertToBrailleRequest(CalculatorWebApplication.CalculatorService.ConvertToBrailleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public ConvertToBrailleRequestBody() {
        }
        
        public ConvertToBrailleRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBrailleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.ConvertToBrailleResponseBody Body;
        
        public ConvertToBrailleResponse() {
        }
        
        public ConvertToBrailleResponse(CalculatorWebApplication.CalculatorService.ConvertToBrailleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToBrailleResult;
        
        public ConvertToBrailleResponseBody() {
        }
        
        public ConvertToBrailleResponseBody(string ConvertToBrailleResult) {
            this.ConvertToBrailleResult = ConvertToBrailleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueCount", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.GetValueCountRequestBody Body;
        
        public GetValueCountRequest() {
        }
        
        public GetValueCountRequest(CalculatorWebApplication.CalculatorService.GetValueCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public GetValueCountRequestBody() {
        }
        
        public GetValueCountRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.GetValueCountResponseBody Body;
        
        public GetValueCountResponse() {
        }
        
        public GetValueCountResponse(CalculatorWebApplication.CalculatorService.GetValueCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetValueCountResult;
        
        public GetValueCountResponseBody() {
        }
        
        public GetValueCountResponseBody(int GetValueCountResult) {
            this.GetValueCountResult = GetValueCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap>, CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CircleA(double firstNumber) {
            return base.Channel.CircleA(firstNumber);
        }
        
        public System.Threading.Tasks.Task<double> CircleAAsync(double firstNumber) {
            return base.Channel.CircleAAsync(firstNumber);
        }
        
        public double TriangleA(double firstNumber, double secondNumber) {
            return base.Channel.TriangleA(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<double> TriangleAAsync(double firstNumber, double secondNumber) {
            return base.Channel.TriangleAAsync(firstNumber, secondNumber);
        }
        
        public double SquareA(double firstNumber) {
            return base.Channel.SquareA(firstNumber);
        }
        
        public System.Threading.Tasks.Task<double> SquareAAsync(double firstNumber) {
            return base.Channel.SquareAAsync(firstNumber);
        }
        
        public double RectangleA(double firstNumber, double secondNumber) {
            return base.Channel.RectangleA(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<double> RectangleAAsync(double firstNumber, double secondNumber) {
            return base.Channel.RectangleAAsync(firstNumber, secondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.ConvertToBraille(CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBraille(request);
        }
        
        public string ConvertToBraille(string text) {
            CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest inValue = new CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.ConvertToBrailleRequestBody();
            inValue.Body.text = text;
            CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse retVal = ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).ConvertToBraille(inValue);
            return retVal.Body.ConvertToBrailleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse> CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.ConvertToBrailleAsync(CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBrailleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.ConvertToBrailleResponse> ConvertToBrailleAsync(string text) {
            CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest inValue = new CalculatorWebApplication.CalculatorService.ConvertToBrailleRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.ConvertToBrailleRequestBody();
            inValue.Body.text = text;
            return ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).ConvertToBrailleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.GetValueCountResponse CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.GetValueCount(CalculatorWebApplication.CalculatorService.GetValueCountRequest request) {
            return base.Channel.GetValueCount(request);
        }
        
        public int GetValueCount(string text) {
            CalculatorWebApplication.CalculatorService.GetValueCountRequest inValue = new CalculatorWebApplication.CalculatorService.GetValueCountRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.GetValueCountRequestBody();
            inValue.Body.text = text;
            CalculatorWebApplication.CalculatorService.GetValueCountResponse retVal = ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetValueCount(inValue);
            return retVal.Body.GetValueCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetValueCountResponse> CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.GetValueCountAsync(CalculatorWebApplication.CalculatorService.GetValueCountRequest request) {
            return base.Channel.GetValueCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetValueCountResponse> GetValueCountAsync(string text) {
            CalculatorWebApplication.CalculatorService.GetValueCountRequest inValue = new CalculatorWebApplication.CalculatorService.GetValueCountRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.GetValueCountRequestBody();
            inValue.Body.text = text;
            return ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetValueCountAsync(inValue);
        }
    }
}
